name: sql builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Create settings.xml
      run: |
          mkdir -p $HOME/.m2
          echo "<settings><servers><server><id>github</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
      
    - name: Build & Publish package
      working-directory: ./
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
